2019-12-24 12:35:00 [ WARNING] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f57316ff400>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/48f27dd6c9b6594732f1bb06c0c6fada (connectionpool.py:744)
2019-12-24 12:35:00 [ WARNING] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f57314c6910>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/48f27dd6c9b6594732f1bb06c0c6fada (connectionpool.py:744)
2019-12-24 12:35:00 [ WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f57314c6af0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/48f27dd6c9b6594732f1bb06c0c6fada (connectionpool.py:744)
